### ISSUE TITLE
Partners icons wrong color

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1199]
![Screen Shot 2022-04-28 at 1.00.57 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/38cfdae2-4796-429d-9e98-32f45a263617)

In parters on mobile, the hamburger icon is the wrong color - it should be the detroit primary green color

Breadcrumb on add listing page 

<img width="115" alt="Screen Shot 2022-04-28 at 3 15 16 PM" src="https://user-images.githubusercontent.com/65367387/165847498-355a90d2-b6ec-4a07-b3ea-1c9ebcae5b7f.png">

Leasing agent section
![Screen Shot 2022-04-28 at 6.03.25 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/65810643-57a6-4d22-b3a4-25be55d5b540)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point 1: Any page on partners
1. Minimize your window (or view on mobile) until you can see the menu hamburger icon
2. Notice the icon is green: 
![image](https://user-images.githubusercontent.com/60076088/167489253-33741c0f-942a-4e91-a9ec-3c37e7839315.png)

Entry Point 2: https://detroit-public-dev.netlify.app/listings
1. Click into any listing
2. Notice that all svg icons are green instead of blue:
![image](https://user-images.githubusercontent.com/60076088/167489412-fd299551-a317-4891-9fc9-06d58861cd9e.png)
