### ISSUE TITLE
Detroit mobile - can't scroll on filters 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1248]
On ios devices, the filtering option opens but then won't scroll on neither safari nor chrome.

https://user-images.githubusercontent.com/53269332/167029258-cf55f4c5-e671-4f7f-a044-4e68b9027a7e.MP4

(just imagine me trying to scroll at the end)

**Comment by ColinBuyck** [comment]
I few things I have noticed so far @emilyjablonski @jaredcwhite :

Observations:
-The filter options can be scrolled with two fingers on mobile
-Inconsistently, a one-finger scroll will scroll the listings behind the filter menu rather than the options themselves
-Even when the menu is scrolled with two fingers, the apply button at the bottom of the form is covered by the search bar and can't be clicked

Potential Leads:
-One thought is that the entire label can be clicked to select the checkbox so almost the entire mobile form is technically "clickable"
-Since the properties behind the menu can be scrolled when the drawer is open, the mobile device could be interpreting the filter option menu as some sort of embedded window in which the listings page could scroll with one finger but the filters need two fingers to differentiate from the property scroll.

**Comment by seanmalbert** [comment]
### QA Notes
To review on https://detroit-public-dev.netlify.app/

**Comment by kathyccheng** [comment]
LGTM
