### ISSUE TITLE
Integrate the mapping API if not using Mapbox

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#129]
We're not using mapbox. Instead, we're using the esri/arcgis api.

There's a react-arcgis package as well.

**Comment by avaleske** [comment]
Detroit is wanting to move forward with Mapbox or Google Maps, so pausing work on this.

The work was in PR #604.

The Esri api had a few constraints that made this work difficult, that we should keep in mind if we try it again:

The @esri/react-argis package is convenient, but on import it tries to call `window`, which isn't available on the server for server side rendering, so we need to only load the modules on the client-side code. Details are in https://github.com/Esri/esri-loader/issues/64.

We can also use a technique like [this](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/ssr-esm/) to wrap the whole component in a way that tells next not to try to run the code on the server.

I pursued a different strategy: Just use the underlying esri code that @esri/react-arcgis wraps, which is what a lot of other people do too. For example:
- https://github.com/benelan/arcgis-esm-samples/blob/main/jsapi-create-next-app/components/EsriMap.js
- https://github.com/tomwayson/esri-loader-react-starter-kit/blob/master/src/components/EsriMap/EsriMap.js

The downside of these is that they require esri loadModules to pull the esri javascript from the Esri cdn every time the page loads, instead of importing it like any other dependency and including in the JS bundle as needed. I got error ERR_REQUIRE_ESM when I tried that though: https://community.esri.com/t5/arcgis-api-for-javascript-questions/arcgis-core-with-next-js-error-err-require-esm/td-p/1037947

Open work:
- Figure out how to import that modules directly
- Fix the styling issues.

**Comment by avaleske** [comment]
@willrlin closing with won'tfix
