### ISSUE TITLE
Epic: CSV imports

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#155]
This tracks tickets related to importing data from CSV files; whether that's HRD doing it or the property manager.

Note: there is already capability to build listings from json files and import them via script. This work would encompass creating a UI to do that same thing.

- [x] #200 
- [x] #203 
- [x] #204 
- [x] #227

**Comment by willrlin** [comment]
@anders-schneider @abbiefarr here's an epic for CSV imports, feel free to fill in as needed

**Comment by willrlin** [comment]
Attached find an explanation and sample CSV file. As you can see, the format is flexible, but for availability we will probably need to go with the one row per unit level of detail.

> So our system will basically allow us to pick virtually any field within our system and create a csv template. I created one that includes only available unit info for one of our offices with multiple properties. WE can also add fields to our database for the purpose of linking index fields. I would guess that your system would need to have a unique index field for each community. We could add that field to our system so that any csv uploads would link the data. If we are going to upload all the units in each community, then a unit number field would be needed in order to upload availability info on each unit.

[default.csv](https://github.com/CityOfDetroit/bloom/files/6786436/default.csv)

**Comment by avaleske** [comment]
Sharing my thoughts from our convo during sprint planning:
- I think we should be careful to keep this scope from growing into "handle generic CSVs and provide a UI for transforming data and align CSV columns with database fields". That's a difficult generic problem that could take a whole team several months.
- We should keep as much of this within property managers' hands as possible, but provide them tools to make it easy.
    - Maybe a CSV export from Bloom that includes the fields we expect, along with unique ids, to keep data aligned between updates. We could also have a field for "property_manager_id" that they can use as their own unique identifier
    - We can provide validation tools in the app or as a script.
    - We can provide a sample data transformation script that property managers can then edit for their data, or that we can write for them, maybe even automating an export and upload as a Scheduled Task in Windows. (Note that in past work, automating data flows for customers has been a full time role during a customer engagement. With HRD's resources, a multi-day 1:1 engagement with every property manager is likely impossible.)

We should also think about what v0 for this is. If availability is the focus, maybe we manually enter all the property data for now (or keep it scoped to something only HRD accounts can do) and then only provide tools for bulk updating availability at the building level to property managers.

Or, since availability doesn't change all that often, maybe tools in the UI are enough.

**Comment by willrlin** [comment]
Closing, as most of the discussion has already happened and these are tracked in the label and not in this issue anymore.
