### ISSUE TITLE
Remove the `localhost:3000/applications/.*` paths

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#159]
We don't want someone to point their browser at e.g. `localhost:3000/applications/start/choose-language` and be able to see the beginning of the apply-for-housing flow.

Note: I don't think it's necessary for us to delete the Next code that defines these UI components (in case we want them in the future). The goal of this issue is just to help prevent a user from ever being able to see those UI components.

**Comment by pfeeny5** [comment]
Notes:
Sites > Public > Pages > Applications : start of application and subsequent pages are created
ListingView.tsx : ability to change "Apply Online" button destination via `internalFormRoute` of `ApplicationSection` component

**Comment by willrlin** [comment]
I asked @pfeeny5 to see if there was a way in NextJS to disable routing to any pages in a subdomain (like everything under `applications/`) so that we could leave the pages there, but not generate them. Hopefully there's a way to do it _without_ having to add a router call in every page that says "if disabled, re-route to somewhere else or give a 404".

**Comment by pfeeny5** [comment]
@willrlin look at [this](https://lifesaver.codes/answer/next-%7Bdev-build%7D-command-should-ignore-tests-dir) possible solution.  We could potentially add excludeFile: (./applications/*).  Alternative flags to accomplish similar thing here: https://github.com/vercel/next.js/issues/2332

**Comment by willrlin** [comment]
Try it out and see! Success would mean that going to `localhost:3000/applications/start/choose-language` directly would return 404.

**Comment by pfeeny5** [comment]
@willrlin Getting stuck.  Have pushed a branch `feature/pfeeny-exclude-applications-pages` with latest try, but doesn't seem to do anything.  Was leveraging this [resource](https://stackoverflow.com/questions/52059366/how-to-exclude-directory-from-getting-bundled-by-webpack).

**Comment by willrlin** [comment]
I'm looking into this now.

**Comment by willrlin** [comment]
I was googling around and it seems like mostly anything we do here would come out as a hack, there have been a bunch of times where people propose adding exclusions to Next's `pages/` folder, but those get rejected or shown workarounds like using the `next.config.js`. The link from the previous comment seemed mostly about webpack config instead of `next.config.js` and I couldn't find anything about `module.rules` in [this type definition of next.config.js](https://github.com/vercel/next.js/blob/canary/packages/next/server/config-shared.ts#L32).

**Comment by willrlin** [comment]
I also tried using the `next.config.js` to simply redirect any path from `/applications` to `/404` and that didn't seem to work either.

**Comment by willrlin** [comment]
I think we should just delete it entirely; we or future developers can always restore it from upstream pretty easily.

**Comment by pfeeny5** [comment]
@willrlin Confirming deleting applications folder from the public side forces the correct 404 errors for all application pages.  Should we just update our git ignore to include ./sites/public/applications/*?

**Comment by willrlin** [comment]
If you use `.gitignore` then the files effectively won't be in the repo, but we will still have stale files around, which could definitely get confusing for future maintainers. I think we should actually delete them from our repository so that it's clear they should not be there and future developers can simply add them back in.
