### ISSUE TITLE
Det: Issues Filtering Listings on Mobile

### ISSUE THREAD

**Issue by iph-97** [CityOfDetroit/bloom#1641]
A city staff person reported they were unable to scroll on the filter window on mobile when browsing listings. They said, "I was trying to look up a property to see if it was listed on Detroit home connect and I was actually unable to apply the filters in the "find rentals for you" section. The problem is that the "done" and "clear" buttons are below the screen on my phone, and I cannot scroll up to see them and click on them at the same time. I think we need a little more space below those buttons or something." I was able to replicate this issue and took this screen recording for a more clear illustration. This is a low priority issue. 
[Uploading... RPReplay_Final1696253842.MP4]

**Comment by ludtkemorgan** [comment]
Initial findings: 
- This is only happening on phones.
- We are not using the "actions" section of the drawer which is meant to have the buttons stay on the bottom of the screen. I don't know if that was intentional or not.
- There was some minor overrides added to this when pulling in the ui-c component

@sarahlazarich This might take a bit of investigating, but I think it's a good ticket to pull into this sprint if somebody is looking for a small bit of work

**Comment by emilyjablonski** [comment]
QA Notes
This needs to be tested on a mobile phone. You can check out the [deploy preview link](deploy preview link) and ensure you can scroll down to the buttons.

**Comment by sarahlazarich** [comment]
lgtm!
