### ISSUE TITLE
Bug: unit summary on listings page not showing up

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#183]
Seems like something else that was broken by #162.

**Comment by willrlin** [comment]
Seems like the transform in [listing.dto.ts](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/src/listings/dto/listing.dto.ts#L295) is not getting called. I did [a comparison](https://github.com/bloom-housing/bloom/compare/master...CityOfDetroit:main) of our source with `bloom-housing/bloom` and I couldn't find anything that would point to where we may be differing except the `backend/core/src/listings/listings.service.ts`.

**Comment by willrlin** [comment]
Oddly the same function in `listing.dto.ts` is getting called just fine in the detailed listing page, just not the overall `/listings` page.

**Comment by abbiefarr** [comment]
The unitsSummarized property isn't being populated in the listings dto, likely for the reason you mentioned above.

I was afraid that the pagination feature I recently added may have broken this, because the way we're fetching the listings is different now. But I did a comparison between the listings that are fetched in the sites/public/index.ts page (which uses the old way) and the listings.ts page (which uses the new way), and neither requests have unitsSummarized populated, so that doesn't seem like the cause.

**Comment by abbiefarr** [comment]
But I still have a suspicion that the pagination PR is what broke this. My guess is that it's something to do with the new way we're requesting listings, and that unitsSummarized isn't populated by the time we display the main listings page, but it has been populated by the time you click on a specific listing and navigate to that page. That would explain why we see it in one place but not the other.

**Comment by abbiefarr** [comment]
I tried running the portal from the upstream merge commit, before the pagination PR, and it's broken at that point, so it's not that. But I still see that the unitsSummarized is not populated at the main listings page but magically populated by the time you get to the individual listing page.

**Comment by abbiefarr** [comment]
The way we're fetching the listing for the main/listings pages and for the individual listing page is different. 

For the index page (this doesn't work, `unitsSummarized` isn't populated):
`process.env.listingServiceUrl + "?filter[$comparison]=<>&filter[status]=pending"`

For the main listings page (this doesn't work, `unitsSummarized` isn't populated):
`listingsService?.list(params)`

For the individual listing page (this works):
`await axios.get(\`${process.env.backendApiBase}/listings/${context.params.id}\`)`

**Comment by willrlin** [comment]
Does that differ compared to upstream? Since it definitely works upstream.

**Comment by anders-schneider** [comment]
Recording a thing I realized: backend-swagger understands `PaginatedListings.items` to be a `Listing` array, *not* a `ListingDto` array: https://github.com/CityOfDetroit/bloom/blob/31b540e3f674ece9e2da1d269fa76b935f60e7a3/backend/core/types/src/backend-swagger.ts#L3382

In our (non-auto-generated code), we never explicitly define `PaginatedListings`; we only define `PaginatedListingsDto` [here](https://github.com/CityOfDetroit/bloom/blob/31b540e3f674ece9e2da1d269fa76b935f60e7a3/backend/core/src/listings/dto/listing.dto.ts#L300). Maybe the `PaginationFactory` is responsible for the fact that backend-swagger only knows about `Listing[]` and not `ListingDto`? (And caveat: I'm not sure that this is responsible for this bug, but it feels worth looking into.)

I tried manually changing `PaginatedListings` to contain `ListingDto` (in backend-swagger), but then ran into issues on the frontend (e.g. in [`ListingsList.tsx`](https://github.com/CityOfDetroit/bloom/blob/main/ui-components/src/page_components/listing/ListingsList.tsx)) getting it to import `ListingDto`, since we can't import `ListingDto` from "@bloom-housing/backend-core/types". (I wanted to do this b/c there are a couple places in that `ListingsList.tsx` file where it has the type as `Listing` instead of `ListingDto`.) I think since `ListingDto` is the entity that has the `unitsSummarized` method, the frontend needs to know about `ListingDto`? i.e. if it doesn't, then `listing.unitsSummarized` will always be undefined, no?

**Comment by willrlin** [comment]
But when backend-swagger is generated, it [removes all the Dto's from the types](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/scripts/generate-axios-client.ts#L15), so I think this `Listing` is supposed to correspond to a `ListingDto`? But then there are also entity definitions, so I don't know how those play into this.

**Comment by anders-schneider** [comment]
Recording what I figured out:

- `TransformOperationExecutor.transform` (in `node_modules/class-transformer/TransformOperationExecutor.js`) is what calls the `unitsSummarized` method in Exygy's code. This happens as part of the serialization of the response when the "listings" controller is responding to `GET /listings`.
- In our code, we aren't calling `unitsSummarized` at the same point (so the serialized response doesn't include the `unitsSummarized` field). In that `transform` method, we *do* have a `unitsSummarized` key, but when we go to access it:

```
subValue = value[valueKey];
```

`subValue` comes back `undefined`. When printing out `value`, our code reports that it's a `Listing` (and doesn't have `units` or `unitsSummarized` and Exygy's code reports that it's a `ListingDto` and does have those two fields). That seems to be the crux, but I haven't figured out why `TransformOperationExecutor.transform` thinks the `value` to be serialized is a `Listing` and not a `ListingDto`. (Hunch: it may have to do with `PaginationFactory`.)
