### ISSUE TITLE
Support multiple values per filter

### ISSUE THREAD

**Issue by abbiefarr** [CityOfDetroit/bloom#285]
The pieces of work involved in this ticket:

- [ ] Changing the filter types in `ListingsFilterParams` to arrays
- [ ] Updating the filter helper that decodes a frontend url to expect comma-separated list of values per filter, and to apply them appropriately

**Comment by avaleske** [comment]
One thing that might make this easier would be to not use `ListingFilterParams` as the filter state storage class on the frontend form. Instead, we might want one that's better suited to the things the frontend cares about.

When reviewing one of @abbiefarr's PRs I suggested re-using the `ListingFilterParams` on the frontend to reduce code duplication, but that might've been the wrong call, for a few reasons @elenm discovered as she was adding the senior housing filter:
- `ListingFilterParams` has a `$comparison` property, which is confusing because the only time the frontend needs to care about the $comparison is when it's encoding the backend URL. Otherwise, as far as the frontend is concerned, the comparison is implicit in the filter (for example, we can assume a filter like `minRent` is going to use a `>` comparison)
- The types of the generated swagger interface aren't arrays, even though the backend code knows how to handle arrays, because the `@ApiProperty` decorator on the field in ListingFilterParams doesn't specify the type as an array. Convincing swagger to generate code with the right types might be difficult and more trouble than just having another similar object on the frontend that the form uses to store state.

Re this frontend filter state object:
- `decode/encodeFrontendUrl()` could take and produce this object
- `encodeBackendUrl()` could also take this object to produce the backend URL, looking up the comparisons in the map it currently uses.
- The keys of this object could be computed from the values of ListingFilterKeys, the same way the properties of `ListingFilterParams` are.

**Comment by willrlin** [comment]
Is this necessary for the product anymore? If we assume that zipcodes already works with comma separated values.

**Comment by willrlin** [comment]
No, I guess I meant do we really need to change anything technically to support multiple neighborhoods or community types? Can we not just have it encoded in the frontend url with comma separated values like the zipcode? And then backend we'd just use the `IN` comparison type.

**Comment by abbiefarr** [comment]
Oh right, I think this is technically already supported since #356, yes?

**Comment by willrlin** [comment]
Sounds good, closing this. @avaleske can re-open if there's more work to do.
