### ISSUE TITLE
Pagination Polish

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#313]
Some fixes for the paginator:
- Add number of pages to the paginator, so it shows "Page X of Y"
- Next / Prev buttons are at the edges of the page on desktop, instead of at the edges of listing column container
- Pagination maybe? should be sticky if multiple pages on desktop?

**Comment by anders-schneider** [comment]
One more thing I discovered: when there are no items, the pagination bar doesn't look good:

![image](https://user-images.githubusercontent.com/8754454/135676058-62b2ee34-c55f-441a-b721-387dbbf6260a.png)

(I got there by (a) logging into the partner portal, (b) clicking on a listing, (c) appending "/flags" to the url)

An idea: just get rid of the "page x of y" (but keep the "(0 total listings)")

**Comment by anders-schneider** [comment]
The last thing in this ticket: should the pagination bar be sticky on desktop view? I experimented with it (by just setting the `sticky={true}` param on the `AgPagination` component) and have a slight preference against it being sticky - it just "feels more natural" to me to have the "next / prev" at the bottom of the page. But I would love for someone else to have strong feelings in one direction or the other :)

I'll close this ticket, but invite anyone with pro-sticky-pagination-bar feelings to reopen (it'd be easy to implement, since the "sticky" CSS class has already been defined).
