### ISSUE TITLE
Open tickets for UI differences to mocks

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#318]
Update UI to reflect recent changes and user testing mocks.

- [ ] #342 
- [ ] #343 
- [x] #344 
- [ ] #345 
- [ ] #346 
- [ ] #347 
- [ ] #348 
- [ ] #349 
- [ ] #350 
- [ ] #329 
- [ ] #330 
- [ ] #328 
- [ ] #307

**Comment by willrlin** [comment]
Do you think we can get all of this UI work done this sprint? I think we should push some of it to make sure we're getting all the previously committed M9 stuff done.

**Comment by willrlin** [comment]
Especially ones where we may be blocked on getting certain assets.

**Comment by anders-schneider** [comment]
I think each of the tickets is a size 1 or 2, so feasible for us to get most of them done (and I'm a little under-committed this sprint). The only reason to prioritize them would be to unblock using our deployed site (instead of mocks) when Gabe/Safiya/etc. talk to property managers. But otherwise agreed that it's probably not great to explode the scope of M9 :)

**Comment by willrlin** [comment]
@anders-schneider @pfeeny5 - which one of these was a duplicate to #328?

**Comment by willrlin** [comment]
Closing now that we have these tickets to track the remaining differences.
