### ISSUE TITLE
[Bug] unit summary on edit page doesn't reflect current edits

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#334]
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE:
1. edit a listing in the partner portal
2. select "individual units"
3. delete all of one type of unit

EXPECTED RESULTS:
When you select "Unit Types", it should show the current unit summary based on the edits made to the listing (tempUnits in `sites/partners/src/listings/PaperListingForm/index.tsx`). But it's just based on `listing?.unitsSummarized`, so it won't update.

OBSERVED RESULTS:
The summary doesn't update.

**Comment by willrlin** [comment]
This may be a difficult thing to do right now since we only calculate the unitsSummarized on the listing once the listing is saved into the database. But we will have to do this same thing eventually (temporarily store the summary until you click save on the form).

**Comment by willrlin** [comment]
FYI @abbiefarr @anders-schneider

**Comment by abbiefarr** [comment]
I believe this bug is obsolete. We expect summary and unit views to show different data, and to not clobber each other when changed. We may even disable the individual units view for Detroit.

It's on Bloom's roadmap to derive the summary table from the units table, but I think that's out of scope for us.
