### ISSUE TITLE
[Bug] form validation for zipcode filter doesn't work

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#429]
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE:
1. Attempt to put an invalid zip code like "aaa".
2. Press "apply filters"

EXPECTED RESULTS:
The error should be displayed saying to specify the zip code in the correct format.

OBSERVED RESULTS:
The error is not displayed, but the cursor moves back to the zip code field and it won't let you apply the filters.

ADDITIONAL INFORMATION:
I've tried many variations of how to do this using the standard react-hook-form and the way other parts of Bloom work, but nothing seems to show the error in the form. I'm wondering if this is because the Modal is outside of the normal DOM hierarchy. I found these sites that talks about using portal, which Exygy already does in the Overlay component:
- https://dev.to/email2vimalraj/form-in-modal-using-react-hooks-mistakes-and-lesson-learnt-19b4
- https://reactjs.org/docs/portals.html

look into react select component, 57 zip codes in detroit

**Comment by anders-schneider** [comment]
Also: if you click into the "zip code" field but leave it blank (because you don't want to filter on zip codes after all), it does the same thing where the cursor moves back to the zip code field and it won't let you apply the filters. So once you've started to apply a zip code filter, you forever after have to apply a zip code filter (maybe unless you refresh the page).

**Comment by willrlin** [comment]
See some more info here: https://github.com/bloom-housing/bloom/discussions/1400#discussioncomment-1240900
