### ISSUE TITLE
scope out work to have csv import modify existing listings

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#513]
instead of just writing to the database once

**Comment by anders-schneider** [comment]
Note from property manager sync:
- We want this script to be something we can run more than once (i.e. whereas the existing CSV import script is intended to be run just once as a one-off upload, _this_ script should be able to be run multiple times). The reason: we expect to get responses to the survey in an ongoing way.
   - Note: re-running this script will clobber any changes that property managers have made through the partner portal. This will be okay in the near-term (until we launch the partner portal) and once we have launched the partner portal, we'll just need to have a bunch of warnings (and maybe even a way to check when the listing was last updated in the script itself?).
- To speed this work up, we might prioritize ingesting a subset of the [fields](https://github.com/CityOfDetroit/bloom/issues/396#issuecomment-909624118) instead of all of them. Gabe is a good point person for figuring out which subset of fields is the most important.
   - We could mark "ingesting the other fields" as follow-on work.

**Comment by anders-schneider** [comment]
I created #567 and #568 with all of my thoughts about what this import script should do. Those tickets are (I believe) actionable and just require coding (no/few product-level questions).
