### ISSUE TITLE
Migrate filters to use units summary

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#530]
The availability filter currently looks up the number of available units in the Units Summary table. This may not work for listings that don't use the unit summary table, and instead include every unit in the units table.

It seems like we have two options to make this work:
- Each time we write to the units table for a listing, update the corresponding units summary rows.
- Update the filter to also check the units table, if the units summary table is empty.

**Comment by abbiefarr** [comment]
We'll have to consider this for bedroom and rent filters as well (and potentially more), so ideally we'll have a general solution for whether to use the units or the units summary table for queries.

**Comment by abbiefarr** [comment]
As kind of a hack, we've been using `disableUnitsAccordion` to determine if we're editing the summaries or the units table. This is also a column in the listings table. We could potentially use this setting to determine how we fetch filters.

E.g. if `disableUnitsAccordion` is true for the listing (i.e. the PM chose to use summaries instead of individual units) then we filter on the summary table. If it's false, we filter on the units table.

**Comment by abbiefarr** [comment]
To make this less hacky (and more contributeable upstream), I think we should add a column to the `listings`table (and a corresponding radio in the listings form) letting partners pick which table they want to use. Then when filtering we choose our inner query based on this listing property.

**Comment by abbiefarr** [comment]
Ok, pivoting on this a bit. After discussing with @willrlin I think it's likely that Exygy will deliver the link between the units and summary table before we wind up getting any units data, so it makes more sense to simplify this and just migrate all the filters to check summary data.
