### ISSUE TITLE
Add final screen in eligibility questionnaire

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#691]
Add final screen in eligibility questionnaire to explain what the filter did and what to expect

**Comment by willrlin** [comment]
Do you have access to [the figma](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=242%3A119)?

**Comment by jnowell** [comment]
Just heard back from Safiya about content. She says this final screen should read: "Thank you for checking how you qualify for affordable housing. Because affordable housing can be reserved for certain age groups or income levels, we have filtered our property listings based on your household characteristics. We hope you find housing that meets your needs. It's important to note that a good portion of affordable housing has a waitlist, but calling properties you're interested in is a good way to get on waitlists or learn of immediate openings." She says the button should simply say "Show Listings".

**Comment by plunkettgoogle** [comment]
This was added in #741, but will also be moved when issue #876 is addressed.
