### ISSUE TITLE
[Email/SMS] Add opt in/opt checkbox for SMS notifications

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#706]
What feature is this part of?
"New Listing" Email/SMS Notifications #695

**Comment by jnowell** [comment]
Talked with Gabe about this a little bit last week, so think we have a decent idea of how we want this to work. Bloom has on their [Figma](https://www.figma.com/file/i3IAkbjv4nVPKg1d1E1g1d/bloom-accounts?node-id=333%3A2169) page a design indicating how opting in to email notifications would work (see below).

What we imagine is that SMS notification would work similarly, with a text field in the Add/Update Account page, and below it a checkbox to opt in to SMS notifications (so there would be separate checkboxes, one for email notifications, another for SMS). 

There should also be a way to opt-out in the email/SMS itself (I'm guessing Twilio has something like this built-in, but not 100% sure). 

LMK if there's any outstanding questions, otherwise we can probably un-assign from me and hand it over to eng.

![email_notification](https://user-images.githubusercontent.com/394908/139687280-07381ecb-4153-4522-92fa-6ec0a02e727e.png)
