### ISSUE TITLE
Detroit - Unit Group Data Model Updates 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#986]
We need the following fields added to the unit summary model:

- add bathroomMin - number - nullable
- add bathroomMax - number - nullable
- add openWaitList - boolean - default open
- add amiChartId - uuid - nullable
- add rentTypeId - uuid - nullable
- update rent to be rentMin and rentMax
- rename (total --> unitGroupQuantity, available--> unitGroupVacant)
- remove minimum monthly income 

We will also need to support 
* Multiple Unit Types (so the unit group can include 1BR, 2BR, 3BR for example) 
* We'll need to support repeating AMI. So each unit group could have multiple sets of 
  * AMI Chart, AMI Percentage, Rent Type (%, Flat), Rent Amt (% or $)

See Mockup for clarity too 
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5214%3A169607

**Comment by kathyccheng** [comment]
@pbn4 we had to make a few extra updates to the data model after seeing all the unit group data. I tried to capture them in the details, but if you have any questions, you can ping @seanmalbert

**Comment by pbn4** [comment]
@kathyccheng  

> rename (total --> unitGroupQuantity, available--> unitGroupVacant)

I think this change could be solely done on frontend. Is there a good point for changing the API and DB schema just for this rename?

**Comment by pbn4** [comment]
@seanmalbert @kathyccheng Updating the model generates following SQL changes to the existing data:

```
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "monthly_rent_as_percent_of_income"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "ami_percentage"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "minimum_income_min"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "minimum_income_max"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "unit_type_id"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "monthly_rent_min"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "monthly_rent_max"`);
        await queryRunner.query(`ALTER TABLE "units_summary" ADD "bathroom_min" integer`);
        await queryRunner.query(`ALTER TABLE "units_summary" ADD "bathroom_max" integer`);
```

I assumed that since it's about to drop data in this table I should migrate it first to a new related entity I called UnitsSummaryAmiLevel (one to many). Basically create a single row with data which is about to be dropped in the old table and connect it to the old table. 
Which one
```
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "monthly_rent_min"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "monthly_rent_max"`);
```

should one should I use to fill `flatRentValue`column?

Also just wanted to make sure that 
```
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "minimum_income_min"`);
        await queryRunner.query(`ALTER TABLE "units_summary" DROP COLUMN "minimum_income_max"`);
```

will completely drop minimum income data as there is no equivalent in the new model. Is that correct?

**Comment by seanmalbert** [comment]
@pbn4 ,
Since we don't have any real data yet in Detroit, we're free to drop columns without migrating them. For the seeds, if you want to use the monthlyRentMax value as the flatRentValue, then you can, but it shouldn't really matter. The new import script based off of the new spreadsheet getting put together should be clear on the flat rent value.

**Comment by pbn4** [comment]
@seanmalbert I'm not sure what to do about this one test for unit groups: 

```
    it("sorts listing.unitsSummary by number of bedrooms (ascending)", async () => {
      const listings = await supertest(app.getHttpServer()).get("/listings?limit=all").expect(200)

      for (const listing of listings.body.items) {
        if (listing.unitsSummary.length > 1) {
          for (let i = 0; i < listing.unitsSummary.length - 1; ++i) {
            const currentUnitsSummary = listing.unitsSummary[i]
            const nextUnitsSummary = listing.unitsSummary[i + 1]
            expect(currentUnitsSummary.unitType.numBedrooms).toBeLessThanOrEqual(
              nextUnitsSummary.unitType.numBedrooms
            )
          }
        }
      }
    })
```

since now unit group has multiple unit types. How should the sorting work now?
